tg = webread(['http://webcritech.jrc.ec.europa.eu/SeaLevelsDb/Home/' ...
              'TideGaugeDetails/50']);
tg = regexp(tg,'<h3>Harmonics Constants</h3>','split');
tg = tg{2};
tgNoW = regexprep(tg,'\s*','');
exp = ['<tdclass="text-centertext-grid">[^<]*</td><tdclass="text-' ...
       'righttext-grid">[^<]*</td><tdclass="text-righttext-grid">' ...
       '[^<]*</td><tdclass="text-righttext-grid">[^<]*</td>'];
tg1 = regexp(tgNoW,exp,'match');
coeffsStr = regexp(tg1,'\d+\.?\d*(E[+-]\d*)?','match');
coeffs = reshape(cell2mat(cellfun(@(x) cellfun(@str2num,x),coeffsStr, ...
                                  'UniformOutput',false)),4,[])';